In [2]:
import numpy as np
student = np.dtype([('name', np.unicode_,  16), ('age', 'i1'), ('marks','f4')])
a = np.array([('abc', 21, 50), ('xyz', 18, 75)], dtype = student)
print(a)

[('abc', 21, 50.) ('xyz', 18, 75.)]


In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [10]:
print(np.arange(0,70,3, dtype='int'))

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69]


In [11]:
print(np.arange(24).reshape(2, 4, 3))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [23]:
print(np.zeros(6))
s = 'Hello World'
print(np.fromiter(s, dtype = 'U1'))

[0. 0. 0. 0. 0. 0.]
['H' 'e' 'l' 'l' 'o' ' ' 'W' 'o' 'r' 'l' 'd']


In [24]:
print(np.transpose(np.arange(12).reshape(3,4)))

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [33]:
a = np.arange(12).reshape(3,4)
b = np.zeros(12, dtype='int').reshape(4,3)
for i in range(0,3):
    for j in range(0,4):
        b[j][i] = a[i][j]
print(b)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [34]:
print(np.eye(10, dtype='int'))

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [36]:
ds1 = np.genfromtxt('./Datasets/Sports.csv', dtype='U15', delimiter=',')
ds2 = np.genfromtxt('./Datasets/Mushroom.csv', dtype='U15', delimiter=',')
ds3 = np.genfromtxt('./Datasets/D3.csv', dtype='U15', delimiter=',')

In [37]:
print(ds1, "\n\n", ds2, "\n\n", ds3)

[['Sky' 'Temperature' 'Humidity' 'Wind' 'Water' 'Forecast' 'EnjoySport']
 ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same' 'Yes']
 ['Sunny' 'Warm' 'High' 'Strong' 'Warm' 'Same' 'Yes']
 ['Rainy' 'Cold' 'High' 'Strong' 'Warm' 'Change' 'No']
 ['Sunny' 'Warm' 'High' 'Strong' 'Cool' 'Change' 'Yes']] 

 [['Color' 'Size' 'Shape' 'Land' 'Air humidity' 'Texture' 'P/NP']
 ['Red' 'Small' 'Round' 'Humid' 'Low' 'Smooth' 'Poisonous']
 ['Red' 'Small' 'Elongated' 'Humid' 'Low' 'Smooth' 'Poisonous']
 ['Grey' 'Large' 'Elongated' 'Humid' 'Low' 'Rough' 'Non-poisonous']
 ['Red' 'Small' 'Elongated' 'Humid' 'High' 'Rough' 'Poisonous']] 

 [['Size' 'Colour' 'Shape' 'Label']
 ['Big' 'Red' 'Circle' 'No']
 ['Small' 'Red' 'Triangle' 'No']
 ['Small' 'Red' 'Circle' 'Yes']
 ['Big' 'Blue' 'Circle' 'No']
 ['Small' 'Blue' 'Circle' 'Yes']]


In [ ]:
np.dot()