<h1><u>Numpy</u></h1>

In [1]:
import numpy as np
student = np.dtype([('name', np.unicode_,  16), ('age', 'i1'), ('marks','f4')])
a = np.array([('abc', 21, 50), ('xyz', 18, 75)], dtype = student)
print(a)

[('abc', 21, 50.) ('xyz', 18, 75.)]


In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [3]:
print(np.arange(0,70,3, dtype='int'))

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69]


In [4]:
print(np.arange(24).reshape(2, 4, 3))

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [5]:
print(np.zeros(6))
s = 'Hello World'
print(np.fromiter(s, dtype = 'U1'))

[0. 0. 0. 0. 0. 0.]
['H' 'e' 'l' 'l' 'o' ' ' 'W' 'o' 'r' 'l' 'd']


In [6]:
print(np.transpose(np.arange(12).reshape(3,4)))

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [7]:
a = np.arange(12).reshape(3,4)
b = np.zeros(12, dtype='int').reshape(4,3)
for i in range(0,3):
    for j in range(0,4):
        b[j][i] = a[i][j]
print(b)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [8]:
print(np.eye(10, dtype='int'))

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [25]:
ds1 = np.genfromtxt('./Datasets/Sports.csv', dtype='U15', delimiter=',')
ds2 = np.genfromtxt('./Datasets/Mushroom.csv', dtype='U15', delimiter=',')
ds3 = np.genfromtxt('./Datasets/D3.csv', dtype='U15', delimiter=',')

In [10]:
print(ds1, "\n\n", ds2, "\n\n", ds3)

[['Sky' 'Temperature' 'Humidity' 'Wind' 'Water' 'Forecast' 'EnjoySport']
 ['Sunny' 'Warm' 'Normal' 'Strong' 'Warm' 'Same' 'Yes']
 ['Sunny' 'Warm' 'High' 'Strong' 'Warm' 'Same' 'Yes']
 ['Rainy' 'Cold' 'High' 'Strong' 'Warm' 'Change' 'No']
 ['Sunny' 'Warm' 'High' 'Strong' 'Cool' 'Change' 'Yes']] 

 [['Color' 'Size' 'Shape' 'Land' 'Air humidity' 'Texture' 'P/NP']
 ['Red' 'Small' 'Round' 'Humid' 'Low' 'Smooth' 'Poisonous']
 ['Red' 'Small' 'Elongated' 'Humid' 'Low' 'Smooth' 'Poisonous']
 ['Grey' 'Large' 'Elongated' 'Humid' 'Low' 'Rough' 'Non-poisonous']
 ['Red' 'Small' 'Elongated' 'Humid' 'High' 'Rough' 'Poisonous']] 

 [['Size' 'Colour' 'Shape' 'Label']
 ['Big' 'Red' 'Circle' 'No']
 ['Small' 'Red' 'Triangle' 'No']
 ['Small' 'Red' 'Circle' 'Yes']
 ['Big' 'Blue' 'Circle' 'No']
 ['Small' 'Blue' 'Circle' 'Yes']]


In [11]:
a = np.mat('4 3; 2 1')
b = np.mat('1 2; 3 4')
print(a, "\n\n", b, "\n\n", np.matmul(a,b), "\n\n", a@b)

[[4 3]
 [2 1]] 

 [[1 2]
 [3 4]] 

 [[13 20]
 [ 5  8]] 

 [[13 20]
 [ 5  8]]


In [12]:
a = np.array([[1,2,3],[3,4,5],[4,5,6],[7,8,9]])
print(np.mean(a), "\n\n", np.median(a))

4.75 

 4.5


In [13]:
print(np.var([1,2,3,4]), "\n\n", np.std([1,2,3,4]))

1.25 

 1.118033988749895


In [14]:
a = np.array([[4,7], [2,6]])
print(np.linalg.matrix_rank(a), end=", ")
print(np.linalg.det(a), end=",\n")
print(np.linalg.inv(a), end=".\n")

2, 10.000000000000002,
[[ 0.6 -0.7]
 [-0.2  0.4]].


In [15]:
print('x + 2y = 8\n3x + 4y = 18\n\n',np.linalg.solve([[1,2],[3,4]],[8,18]))

x + 2y = 8
3x + 4y = 18

 [2. 3.]


<h1><u>Pandas</u></h1>

In [16]:
import pandas as pd
data = [['Alex', 10], ['Bob', 12], ['Clarke', 13]]
df = pd.DataFrame(data, columns=['Name','Age'])
print(df)

     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13


In [23]:
df.iloc[:,0:1]

Name
0    Alex
1     Bob
2  Clarke

In [30]:
df.loc[1:,['Name']]

Name
1     Bob
2  Clarke

In [27]:
ds1 = pd.read_csv('./Datasets/Sports.csv')
ds2 = pd.read_csv('./Datasets/Mushroom.csv')
ds3 = pd.read_csv('./Datasets/D3.csv')

In [29]:
print(ds1,end="\n\n")
print(ds2,end="\n\n")
print(ds3)

     Sky Temperature Humidity    Wind Water Forecast EnjoySport
0  Sunny        Warm   Normal  Strong  Warm     Same        Yes
1  Sunny        Warm     High  Strong  Warm     Same        Yes
2  Rainy        Cold     High  Strong  Warm   Change         No
3  Sunny        Warm     High  Strong  Cool   Change        Yes

  Color   Size      Shape   Land Air humidity Texture           P/NP
0   Red  Small      Round  Humid          Low  Smooth      Poisonous
1   Red  Small  Elongated  Humid          Low  Smooth      Poisonous
2  Grey  Large  Elongated  Humid          Low   Rough  Non-poisonous
3   Red  Small  Elongated  Humid         High   Rough      Poisonous

    Size Colour     Shape Label
0    Big    Red    Circle    No
1  Small    Red  Triangle    No
2  Small    Red    Circle   Yes
3    Big   Blue    Circle    No
4  Small   Blue    Circle   Yes


In [32]:
df = pd.DataFrame(np.random.randn(5,3),index=['a', 'c', 'e', 'f', 'h'],columns=['one','two','three'])
df = df.reindex(['a','b','c','d','e','f','g','h'])
print(df)

        one       two     three
a  0.599717 -0.503401  1.850396
b       NaN       NaN       NaN
c -0.251753 -1.530888 -0.699592
d       NaN       NaN       NaN
e  1.195238  2.201305  1.736050
f  0.330791 -0.743620 -0.316642
g       NaN       NaN       NaN
h  0.393042 -0.434718  0.838301
